my-store/config/routes.rb
Rails.application.routes.draw do
  mount Workarea::Core::Engine => '/'
  mount Workarea::Admin::Engine => '/admin', as: 'admin'
  mount Workarea::Storefront::Engine => '/', as: 'storefront'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resource :membership, only: :update

    resources :orders, only: [] do
      member { post :reorder }
    end

    resources :organization, only: :index
    resources :organization, only: :create

    post 'join_account', to: 'organization#join_account'
    get 'join_org', to: 'organization#join_org'
    post 'join', to: 'organization#join'
    resource :accounts, only: [:show, :edit, :update] do
      get :transactions
      resources :addresses, controller: 'accounts/addresses'
      resources :credit_cards, controller: 'accounts/credit_cards'
      resources :memberships, controller: 'accounts/memberships'
      resources :orders, only: [:index, :show], controller: 'accounts/orders' do
        member { patch :review }
        collection { get :pending }
      end
    end

    resources :signups, only: [:edit, :update]
  end
end

my-store/app/models/workarea/organization/join_request.rb
module Workarea
  class Organization
    class JoinRequest
      include ApplicationDocument

      field :email, type: String, default: "sample@gmail.com"
      belongs_to :user,
        class_name: 'Workarea::User',
        index: true,
        optional: false
      belongs_to :account,
        class_name: 'Workarea::Organization::Account',
        index: true,
        optional: false

      validates :user, presence: true
      validates :email, presence: true
      validates :account, presence: true
    end
  end
end

my-store/app/models/workarea/storefront/organization.rb
class Workarea::Storefront::Organization
  include Mongoid::Document
  field :name, type: String
  field :organization_name, type: String
end

my-store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

my-store/app/controllers/workarea/storefront/organization_controller.rb
class Workarea::Storefront::OrganizationController < Workarea::Storefront::ApplicationController
  helper Workarea::Storefront::OrganizationsHelper
  def index

  end

  def create
    new_organization = Workarea::Organization.new
    new_organization.name = params[:organization][:name]
    new_organization.save!
    new_account = Workarea::Organization::Account.new
    new_account.organization_id = new_organization.id
    new_account.name = params[:account][:name]
    new_account.payment_terms = params[:account][:payment_terms]
    new_account.tax_code = params[:account][:tax_code]
    new_account.credit_limit = params[:account][:credit_limit]
    new_account.save!
  end

  def join_org

  end

  def join
    current_user = Workarea::User.all.find_by(email: params[:joined][:email])
    account = Workarea::Organization::Account.all.find_by(name: params[:account][:name])
    join_request = Workarea::Organization::JoinRequest.new(
      email: params[:joined][:email],
      user_id: current_user.id,
      account_id: account.id )
    join_request.save!
  end

  def join_account
    @account_params  = []
    org_name = params[:organization][:name]
    @organization_name = org_name
    Workarea::Organization::Account.all.each do |account|
       @account_params  << account.name if account.organization.name == org_name
     end
  end
end

my-store/app/helpers/application_helper.rb
module ApplicationHelper
end

my-store/app/helpers/workarea/storefront/organizations_helper.rb
module Workarea
  module Storefront
    module OrganizationsHelper

      def membership_role_options
        Workarea.config.membership_roles.map do |role|
          [role.titleize, role]
        end
      end

      def payment_term_options
        Workarea.config.payment_terms.keys.unshift(['none', nil])
      end

      def organization_options
        result = []
        Workarea::Organization.all.each {|el| result.unshift(el.name)}
        result.unshift(['none', nil])
      end
    end
  end
end

my-store/app/views/workarea/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

my-store/app/views/workarea/storefront/content_blocks/_captioned_image.html.haml
- view_model.products.each do |product|
  .grid__cell.grid__cell--50.grid__cell--33-at-medium.grid__cell--16-at-wide
    %div.product-summary.product-summary--small{ itemscope: true, itemtype: 'http://schema.org/Product' }
      = render 'workarea/storefront/products/summary', product: product

my-store/app/views/workarea/storefront/organization/create.html.erb
<h1>Hello</h1>

my-store/app/views/workarea/storefront/organization/index.html.haml
- @page_title = t('workarea.organization_accounts.new.page_title')

.view
  .view__header
    .grid
      .grid__cell.grid__cell--50
      .grid__cell.grid__cell--50
        .view__heading
          //= link_to_index_for(@account)
          %h1= t('workarea.organization_accounts.new.page_title')

  .view__container.view__container--narrow

    = form_tag organization_index_path, method: :post, id: 'account_form', data: { unsaved_changes: '' } do

      .section

        .property.property--required
          = label_tag 'organization_name', t('workarea.fields.organization_name'), class: 'property__name'
          = text_field_tag 'organization[name]', @organization, class: 'text-box text-box--i18n', required: true

        .property.property--required
          = label_tag 'account_name', t('workarea.fields.name'), class: 'property__name'
          = text_field_tag 'account[name]', @account, class: 'text-box text-box--i18n', required: true

        .grid.grid--huge
          .grid__cell.grid__cell--25
            .property
              = label_tag 'account_payment_terms', t('workarea.fields.payment_terms'), class: 'property__name'
              = select_tag 'account[payment_terms]', options_for_select(payment_term_options, @account)


          .grid__cell.grid__cell--25
            .property
              = label_tag 'account_tax_code', t('workarea.fields.tax_code'), class: 'property__name'
              = text_field_tag 'account[tax_code]', @account, class: 'text-box text-box--medium'

          .grid__cell.grid__cell--25
            .property
              = label_tag 'account_credit_limit', t('workarea.fields.credit_limit'), class: 'property__name'
              = currency_symbol
              = text_field_tag 'account[credit_limit]', @account, class: 'text-box text-box--medium'



      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.organization_accounts.new.button'), value: 'create_account', class: 'workflow-bar__button workflow-bar__button--update'

my-store/app/views/workarea/storefront/organization/join_account.html.haml
- @page_title = t('workarea.organization_accounts.new.page_title')

.view
  .view__header
    .grid
      .grid__cell.grid__cell--50
      .grid__cell.grid__cell--50
        .view__heading
          //= link_to_index_for(@account)
          %h1= t('workarea.organization_accounts.new.page_title')

  .view__container.view__container--narrow

    = form_tag join_path, method: :post, id: 'account_form', data: { unsaved_changes: '' } do

      .section


        .grid.grid--huge
          .grid__cell.grid__cell--25

            .property.property--required
              = label_tag 'organization[name]', t(@organization_name), class: 'property__name'

            .property
              = label_tag 'account_name', t('workarea.fields.account_name'), class: 'property__name'
              = select_tag 'account[name]', options_for_select(@account_params)

          .grid__cell.grid__cell--25
            .property
              = label_tag 'join_email', t('workarea.fields.joined_email'), class: 'property__name'
              = text_field_tag 'joined[email]', @joined, class: 'text-box text-box--medium'



      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.organization_accounts.new.button'), value: 'join_account', class: 'workflow-bar__button workflow-bar__button--update'

my-store/app/views/workarea/storefront/organization/join_org.html.haml
- @page_title = t('workarea.organization_accounts.new.join_to_organization')

.view
  .view__header
    .grid
      .grid__cell.grid__cell--50
      .grid__cell.grid__cell--50
        .view__heading
          //= link_to_index_for(@account)
          %h1= t('workarea.organization_accounts.new.join_to_organization')

  .view__container.view__container--narrow

    = form_tag join_account_path, method: :post, id: 'account_form', data: { unsaved_changes: '' } do

      .section

        .grid.grid--huge
          .grid__cell.grid__cell--25
            .property
              = label_tag 'organizations_list', t('workarea.fields.organization_list'), class: 'property__name'
              = select_tag 'organization[name]', options_for_select(organization_options, @organization)




      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= button_tag t('workarea.admin.organization_accounts.new.join_account'), value: 'join_account', class: 'workflow-bar__button workflow-bar__button--update'

my-store/app/views/workarea/storefront/style_guides/components/_captioned_image_content_block.html.haml
#captioned-image-content-block.style-guide__subsection

  %h3= link_to_style_guide('components', 'captioned_image_content_block')

  %p A content block that displays an image with a caption. Used for figures in technical documentation.

  .style-guide__example-block
    .captioned-image-content-block
      %figure.captioned-image-content-block__figure
        = image_tag('pig.png', alt: 'An ACME widget in all its glory', class: 'captioned-image-content-block__image')
        %figcaption.captioned-image-content-block__caption An ACME widget in all its glory

my-store/app/views/workarea/storefront/users/logins/new.html.haml
- @title = t('workarea.storefront.users.login_or_create_an_account')

.view

  .login

    %h1= t('workarea.storefront.users.login_or_create_an_account')

    .grid

      .grid__cell.grid__cell--33-at-medium
        %h2= t('workarea.storefront.users.login')
        = form_tag login_path, id: 'login_form', method: 'post', data: { analytics: login_analytics_data.to_json }, class: 'login__form' do
          = hidden_field_tag :return_to, params[:return_to], id: nil
          .property
            = label_tag 'log_in_email', nil, class: 'property__name' do
              %span.property__text= t('workarea.storefront.users.email')
            .value= email_field_tag :email, params[:email], id: 'log_in_email', class: 'text-box', required: true, placeholder: t('workarea.storefront.forms.email_placeholder')
          .property
            = label_tag 'log_in_password', nil, class: 'property__name' do
              %span.property__text= t('workarea.storefront.users.password')
            .value= password_field_tag :password, nil, id: 'log_in_password', class: 'text-box', required: true, autocomplete: 'off'
          .grid.grid--auto
            %p.grid__cell= button_tag t('workarea.storefront.users.login'), value: 'login', class: 'button'
            %p.grid__cell= link_to t('workarea.storefront.users.forgot_password'), forgot_password_path, class: 'text-button'

      .grid__cell.grid__cell--33-at-medium
        %h2= t('workarea.storefront.users.create_account')
        = form_tag users_account_path, id: 'signup_form', method: :post, data: { analytics: signup_analytics_data.to_json }, class: 'login__form' do
          = hidden_field_tag :return_to, params[:return_to], id: nil
          .property
            = label_tag 'create_account_email', nil, class: 'property__name' do
              %span.property__text= t('workarea.storefront.users.email')
            .value
              = email_field_tag :email, params[:email], id: 'create_account_email', class: 'text-box', required: true, placeholder: t('workarea.storefront.forms.email_placeholder')
              - if @user.errors[:email].any?
                %span.value__error= @user.errors[:email].first
          .property
            = label_tag 'create_account_password', nil, class: 'property__name' do
              %span.property__text= t('workarea.storefront.users.password')
            .value
              = password_field_tag :password, nil, id: 'create_account_password', class: 'text-box', required: true, minlength: minimum_password_length, autocomplete: 'off'
              - if @user.errors[:password].present?
                %span.value__error= @user.errors[:password].first
          .button-property
            .value= check_box_tag :email_signup, true, params[:email_signup]
            = label_tag :email_signup, nil, class: 'button-property__name' do
              %span.button-property__text= t('workarea.storefront.users.sign_up_for_email')
          = button_tag t('workarea.storefront.users.create_account'), value: 'create_account', class: 'button', data: { disable_with: loading_indicator(t('workarea.storefront.users.create_account_disabled_text')) }

      .grid__cell.grid__cell--33-at-medium
        %h2= t('workarea.storefront.users.create_organisation')
        = form_tag organization_index_path, id: 'signup_form', method: :get, data: { analytics: signup_analytics_data.to_json }, class: 'login__form' do
          = hidden_field_tag :return_to, params[:return_to], id: nil
          .property
          = button_tag t('workarea.storefront.users.create_organisation'), value: 'create_organisation', class: 'button'
        = form_tag join_org_path, id: 'signup_form', method: :get, data: { analytics: signup_analytics_data.to_json }, class: 'login__form' do
          = hidden_field_tag :return_to, params[:return_to], id: nil
          .property
          = button_tag t('workarea.storefront.users.join_to_organization'), value: 'create_organisation', class: 'button'

    = append_partials('storefront.new_login', user: @user)