my-store/workarea_repeat_block/config/routes.rb
Rails.application.routes.draw do
  Workarea::Admin::Engine.routes.draw do
    scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
      post 'add_repeat_block', to: 'repeat_block#add_repeat_block'
      post 'delete_repeat_block', to: 'repeat_block#delete_repeat_block'
    end
  end
end

my-store/workarea_repeat_block/app/controllers/workarea/admin/repeat_block_controller.rb
module Workarea
  class Admin::RepeatBlockController < Admin::ApplicationController

    def delete_repeat_block
      @content = Content.find(params[:content_id])
      @content = Workarea::Admin::ContentViewModel.new(
        @content,
        view_model_options
      )
      current_block = @content.blocks.find(params[:button])
      current_block.type.fieldsets.pop
      current_block.type.repeat_with_delete
      current_block.type.save!
      current_block.save!
      @content.save!
    end

    def add_repeat_block
      @content = Content.find(params[:content_id])
      @content = Workarea::Admin::ContentViewModel.new(
        @content,
        view_model_options
      )
      current_block = @content.blocks.find(params[:button])
      current_block.type.fieldsets = current_block.type.repeat
      current_block.type.save!
      current_block.save!
      @content.save!
    end
  end
end

my-store/workarea_repeat_block/app/views/workarea/admin/content/_form.html.haml
- return_to_param = params[:return_to].respond_to?(:to_h) ? params[:return_to].to_h : params[:return_to]
- return_to_url = return_to_param.present? ? url_for(return_to_param) : request.path
= hidden_field_tag 'return_to', return_to_url, id: dom_id(block, :return_to)
= hidden_field_tag 'block[type_id]', block.type_id, id: dom_id(block, :type_id)
= hidden_field_tag 'block[position]', params[:new_block][:position], id: dom_id(block, :position) if params[:new_block].present?

.content-editor__form-header
  .align-center
    - if block.new_record?
      = link_to "← #{t('workarea.admin.content.form.cancel')}", return_to_url
    - else
      = link_to "← #{t('workarea.admin.content.form.all_blocks')}", '#', data: { content_editor_form_cancel: '' }

  .grid.grid--middle.grid--center.grid--auto
    .grid__cell
      = content_block_icon(block.icon, title: block.name, class: 'svg-icon svg-icon--gray')
    .grid__cell
      %span.content-editor__form-heading= block.name

.content-editor__form-fields
  .tabs
    - block.fieldsets.each do |fieldset|
      .tabs__panel
        %h2.tabs__heading= fieldset.name
        - fieldset.fields.each do |field|
          = render "workarea/admin/content_blocks/#{field.partial}", field: field, block: block
    - if block.type.repeat_number > 0
      .tabs__panel
        %h2.tabs__heading= t('repeat')
        %table.repeate-table
          - block.type.repeat_number.times do |_|
            %tr
              %th= 'repeat block'
              %th
                =form_tag delete_repeat_block_path, id: "delete_repeat_form1" do
                  =hidden_field_tag 'hidden'
          %tr
            %th
              =form_tag delete_repeat_block_path, id: 'delete_repeat_form' do
                = text_field_tag 'content_id', @content.id, class: 'hidden'
                =button_tag 'delete', value: block.id, class: 'button'
            %th
              =form_tag add_repeat_block_path, id: 'add_repeat_form' do
                = text_field_tag 'content_id', @content.id, class: 'hidden'
                =button_tag 'add', value: block.id, class: 'button'

    .tabs__panel
      %h2.tabs__heading= t('workarea.admin.content.form.display')
      .section
        %span.heading.heading--4
          = t('workarea.admin.content.form.segments')
          - if block.segmented? && block.segments.blank?
            = link_to '#missing-segments-tooltip', data: { tooltip: '' } do
              = inline_svg('workarea/admin/icons/alert.svg', class: 'svg-icon svg-icon--small svg-icon--red')
            #missing-segments-tooltip.tooltip-content
              %p= t('workarea.admin.shared.active_field.no_segments')

        .property
          = label_tag 'block_active_segment_ids', t('workarea.admin.content.form.exclusive_segments'), class: 'property__name'
          = select_tag 'block[active_segment_ids]', options_from_collection_for_select(segments, :id, :name, block.active_segment_ids), multiple: true, data: { select: { placeholder: t('workarea.admin.shared.active_field.select_segments'), allowClear: true } }, id: nil

      .section
        %span.heading.heading--4= t('workarea.admin.content.form.hide_for')
        - Workarea.config.storefront_break_points.each_key do |breakpoint|
          .property
            = hidden_field_tag 'block[hidden_breakpoints][]', '', id: nil
            = check_box_tag 'block[hidden_breakpoints][]', breakpoint.to_s, block.hidden_breakpoints.include?(breakpoint.to_s), id: dom_id(block, "hidden_breakpoint_#{breakpoint.to_s}")
            = label_tag dom_id(block, "hidden_breakpoint_#{breakpoint.to_s}"), nil, class: 'property__name' do
              #{breakpoint.to_s.titleize} #{t('workarea.admin.content.form.devices')}


.content-editor__form-actions
  .grid.grid--auto.grid--center.grid--middle
    .grid__cell
      - if block.new_record?
        = render 'workarea/admin/shared/activate_select', name: 'block[activate_with]'
      - else
        = render 'workarea/admin/shared/publishing_select'

    .grid__cell
      - if block.new_record?
        = button_tag t('workarea.admin.actions.save'), value: 'create_block', class: 'button button--create'
      - else
        = button_tag t('workarea.admin.form.save_changes'), value: 'save_block', class: 'button'

my-store/workarea_repeat_block/app/views/workarea/storefront/content_blocks/_my_block.html.haml
.my-block-content-block
  .grid.grid--flush.grid--center
    - view_model.series.each_with_index do |image, i|
      - unless image.asset.image_placeholder?
        .grid__cell.grid__cell--50-at-medium
          - if image.link.present?
            = link_to image.link, class: 'my-block-content-block__link' do
              = image_tag image.asset.url, alt: image.alt, class: 'my-block-content-block__image'
          - else
            = image_tag image.asset.url, alt: image.alt, class: 'my-block-content-block__image'

my-store/workarea_repeat_block/app/views/workarea/storefront/style_guides/components/_my_block_content_block.html.haml
#my-block-content-block.style-guide__subsection

  %h3= link_to_style_guide('components', 'my_block_content_block')

  %p A content block responsible for the tiled layout of up to 6 images.

  %p A red border has been added to the following examples in order to give clearer distinction between images.

  - (1..4).each do |i|
    %p should support <strong>#{pluralize(i, 'image')}</strong>:
    .style-guide__example-block
      .my-block-content-block
        .grid.grid--flush.grid--center
          - i.times do
            .grid__cell.grid__cell--50-at-medium
              = link_to '#', class: 'my-block-content-block__link' do
                = image_tag 'workarea/storefront/sample.jpg', class: 'my-block-content-block__image', style: 'width: 960px; height: 360px; border: 1px solid red'