my-store/workarea-checkout_auth_step/config/routes.rb
Rails.application.routes.draw do
  Workarea::Storefront::Engine.routes.draw do
    scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
      namespace :checkout do
          get   'authorization', to: 'authorization#authorization'
          patch 'authorization', to: 'authorization#update_authorization'
      end
    end
  end
end

my-store/workarea-checkout_auth_step/app/models/workarea/checkout/steps/authorization.rb
module Workarea
  class Checkout
    module Steps
      class Authorization < Base

        def update(params = {})
          set_order_email(params)

          persist_update
        end


        def complete?
          order.valid?
        end

        private

        def set_order_email(params)
          if params[:email].present?
            order.email = params[:email]
          elsif user.present?
            order.email = user.email
          end
        end

        def persist_update
          order.save
        end

      end
    end
  end
end

my-store/workarea-checkout_auth_step/app/controllers/workarea/storefront/checkout/authorization_controller.rb
module Workarea
  module Storefront
    module Checkout
      class AuthorizationController < CheckoutsController

        # GET /checkout/authorization
        def authorization
          @step ||= Storefront::Checkout::AuthorizationViewModel.new(
            authorization_step,
            view_model_options
          )
        end

        # PATCH /checkout/addresses
        def update_authorization
          authorization_step.update(params)
          if authorization_step.complete?
            completed_authorization_step
          else
            incompleted_authorization_step
          end
        end

        private

        def authorization_step
          @authorization_step ||= Workarea::Checkout::Steps::Authorization.new(current_checkout)
        end

        def completed_authorization_step
          flash[:success] = "Success"
          redirect_to checkout_addresses_path
        end

        def incompleted_authorization_step
          authorization
          render :authorization
        end

      end
    end
  end
end

my-store/workarea-checkout_auth_step/app/views/workarea/storefront/checkouts/_checkout_progress.html.haml
%nav.checkout-progress
  - if @current_user.blank?
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :authorization) }
      = link_to_unless @checkout_step == 'authorization', t('workarea.storefront.checkouts.authorization_step_text'), checkout_authorization_path, class: 'checkout-progress__link'
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :addresses) }
      = link_to_unless @checkout_step.in?(%w(addresses authorization)), t('workarea.storefront.checkouts.addresses_second_step_text'), checkout_addresses_path, class: 'checkout-progress__link'
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :shipping) }
      = link_to_unless @checkout_step.in?(%w(addresses shipping authorization)), t('workarea.storefront.checkouts.shipping_third_step_text'), checkout_shipping_path, class: 'checkout-progress__link'
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :payment) }= t('workarea.storefront.checkouts.payment_fourth_step_text')
  - else
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :addresses) }
      = link_to_unless @checkout_step == 'addresses', t('workarea.storefront.checkouts.addresses_first_step_text'), checkout_addresses_path, class: 'checkout-progress__link'
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :shipping) }
      = link_to_unless @checkout_step.in?(%w(addresses shipping)), t('workarea.storefront.checkouts.shipping_second_step_text'), checkout_shipping_path, class: 'checkout-progress__link'
    .checkout-progress__step{ class: ('checkout-progress__step--active' if @checkout_step == :payment) }= t('workarea.storefront.checkouts.payment_third_step_text')

my-store/workarea-checkout_auth_step/app/views/workarea/storefront/checkouts/_summary.html.haml
.checkout-step-summary

  .checkout-step-summary__step.checkout-step-summary__step--hidden-for-small

    .checkout-step-summary__section
      %h3= t('workarea.storefront.checkouts.email')
      %p= summary.email

    - if summary.show_addresses?
      %h2= t('workarea.storefront.checkouts.addresses')

      - if summary.show_shipping_address?
        .checkout-step-summary__section
          %h3= t('workarea.storefront.checkouts.shipping_address')
          %p= formatted_address(summary.shipping_address)

      .checkout-step-summary__section
        %h3= t('workarea.storefront.checkouts.billing_address')
        %p= formatted_address(summary.billing_address)

      - unless current_page?(checkout_addresses_path)
        %p= link_to t('workarea.storefront.forms.edit'), checkout_addresses_path, class: 'button', data: { analytics: checkout_edit_analytics_data('addresses') }

    = append_partials('storefront.checkout_summary_addresses', summary: summary)

  .checkout-step-summary__step.checkout-step-summary__step--hidden-for-small

    - if summary.show_shipping_options?
      %h2= t('workarea.storefront.checkouts.shipping_options')

      - summary.shippings.each_with_index do |shipping, index|
        - if shipping.show_options?
          .checkout-step-summary__section
            %h3
              - if shipping.partial?
                = t('workarea.storefront.checkouts.shipping_service_with_index', index: index + 1)
              - else
                = t('workarea.storefront.checkouts.shipping_service')
            %p #{shipping.shipping_service.name} - #{number_to_currency(shipping.shipping_total)}
            - if shipping.instructions.present?
              %p= shipping.instructions

          = append_partials('storefront.checkout_summary_shipping_attributes', summary: summary, shipping: shipping, index: index)

      - unless checkout_shipping_path == request.original_fullpath
        %p= link_to t('workarea.storefront.forms.edit'), checkout_shipping_path, class: 'button', data: { analytics: checkout_edit_analytics_data('shipping') }

    = append_partials('storefront.checkout_summary_shipping', summary: summary)

  .checkout-step-summary__step

    %h2= t('workarea.storefront.checkouts.totals')
    %table.table.table--totals
      %tbody
        %tr
          %th
            %span= t('workarea.storefront.orders.subtotal')
          %td= number_to_currency(cart.subtotal_price)
        - if cart.total_adjustments.any?
          - cart.total_adjustments.each do |adjustment|
            %tr
              %th
                %span= adjustment.description
              %td
                - if adjustment.discount?
                  %strong= number_to_currency(adjustment.amount)
                - else
                  %span= number_to_currency(adjustment.amount)

        %tr
          %th
            %span= t('workarea.storefront.orders.shipping')
          %td
            - if !cart.requires_shipping?
              = t('workarea.storefront.checkouts.not_applicable')
            - elsif !summary.shipping_determined?
              = t('workarea.storefront.checkouts.to_be_determined')
            - else
              = number_to_currency(cart.shipping_total)

        %tr
          %th
            %span= t('workarea.storefront.orders.tax')
          %td
            - if summary.taxes_determined?
              = number_to_currency(cart.tax_total)
            - else
              = t('workarea.storefront.checkouts.to_be_determined')

        - if summary.store_credit?
          %tr
            %th
              %span= t('workarea.storefront.orders.store_credit')
            %td
              %strong.table__price-discount −#{number_to_currency(summary.store_credit_amount)}

        = append_partials('storefront.checkout_summary_payment', summary: summary)

        %tr.table__total
          %th
            %span= t('workarea.storefront.orders.total')
          %td= number_to_currency(summary.order_balance)

my-store/workarea-checkout_auth_step/app/views/workarea/storefront/checkouts/addresses.html.haml
- @title = t('workarea.storefront.checkouts.addresses_title')
- @checkout_step = 'addresses'

- content_for :page_aside do
  %h1.visually-hidden= t('workarea.storefront.checkouts.addresses_title')
  = render 'summary', cart: @cart, summary: @summary

.checkout-addresses.view{ data: { analytics: checkout_addresses_view_analytics_data(@cart).to_json } }
  - unless request.get?
    - if @step.order.errors.any?
      - @step.order.errors.full_messages.each do |message|
        = render_message 'error', message, data: { analytics: validation_error_analytics_data('order').to_json }
    - if @step.billing_address.errors.any?
      - @step.billing_address.errors.full_messages.each do |message|
        = render_message 'error', data: { analytics: validation_error_analytics_data('billing_address').to_json } do
          #{t('workarea.storefront.checkouts.billing_address')}: #{message}
    - if @step.shipping_address.errors.any?
      - @step.shipping_address.errors.full_messages.each do |message|
        = render_message 'error', data: { analytics: validation_error_analytics_data('shipping_address').to_json } do
          #{t('workarea.storefront.checkouts.shipping_address')}: #{message}

  = append_partials('storefront.checkout_addresses_top', step: @step)

  = form_tag checkout_addresses_path, method: :patch, id: 'checkout_form', data: { checkout_addresses_form: { defaultShippingAddressId: @step.default_shipping_address_id, defaultBillingAddressId: @step.default_billing_address_id, savedAddresses: @step.saved_addresses }.to_json } do

    - if @step.show_shipping_address?
      .checkout-addresses__section.checkout-addresses__section--shipping
        %h2.checkout-addresses__heading= t('workarea.storefront.checkouts.shipping_address')
        = append_partials('storefront.checkout_shipping_address_top', step: @step)
        .checkout-addresses__fields= render 'workarea/storefront/shared/address_fields', label: 'shipping_address', address: @step.shipping_address

    .checkout-addresses__section.checkout-addresses__section--billing
      %h2.checkout-addresses__heading= t('workarea.storefront.checkouts.billing_address')
      .checkout-addresses__fields.hidden-if-js-enabled= render 'workarea/storefront/shared/address_fields', label: 'billing_address', address: @step.billing_address

    = append_partials('storefront.checkout_addresses_form', step: @step)

    - if @step.show_shipping_address?
      %p= button_tag t('workarea.storefront.checkouts.continue_to_shipping'), value: 'continue', class: 'button button--large', data: { disable_with: loading_indicator(t('workarea.storefront.checkouts.continue_to_shipping_disabled_text')) }
    - else
      %p= button_tag t('workarea.storefront.checkouts.continue_to_payment'), value: 'continue', class: 'button button--large', data: { disable_with: loading_indicator(t('workarea.storefront.checkouts.continue_to_payment_disabled_text')) }

my-store/workarea-checkout_auth_step/app/views/workarea/storefront/checkouts/authorization.html.haml
- @title = t('Authorization')
- @checkout_step = 'authorization'

= form_tag checkout_authorization_path, method: :patch, id: 'checkout_form' do
  - if @step.show_email_field?
    .checkout-authorization__section.checkout-authorization__section--email
      %h2.checkout-addresses__heading= t('workarea.storefront.checkouts.email')
      .property
        = label_tag :email, nil, class: 'property__name' do
          %span.property__requirement.property__requirement--required= t('workarea.storefront.forms.required')
          %span.property__text= t('workarea.storefront.checkouts.email')
        .value
          = email_field_tag :email, @step.email, class: 'text-box', required: true, autocapitalize: 'off', autocomplete: 'email', placeholder: t('workarea.storefront.forms.email_placeholder')
          - if @step.order.errors[:email].present?
            %span.value__error= @step.order.errors[:email].first
      %p
        = t('workarea.storefront.checkouts.login_prompt')
        = link_to t('workarea.storefront.checkouts.login_title'), login_path(return_to: checkout_path), data: { analytics: checkout_login_analytics_data.to_json }
  - if @step.show_email_field?
    %p= button_tag t('workarea.storefront.checkouts.continue_to_addresses'), value: 'continue', class: 'button button--large', data: { disable_with: loading_indicator(t('workarea.storefront.checkouts.continue_to_shipping_disabled_text')) }